steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bible-chatbot', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bible-chatbot']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - bible-chatbot
      - --image=gcr.io/$PROJECT_ID/bible-chatbot
      - --platform=managed
      - --region=us-central1
      - --allow-unauthenticated
      - --port=8080
      - --memory=4Gi
      - --timeout=600s
      - --update-secrets=HF_TOKEN=HF_TOKEN:latest
